# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- import_playbook: oe-linux-acc-setup.yml

- hosts: linux-agents
  any_errors_fatal: true
  gather_facts: true
  become: yes
  tasks:
    - import_role:
        name: linux/jenkins
        tasks_from: slave-setup.yml

    - import_role:
        name: linux/validation
        tasks_from: slave-validation.yml

- import_playbook: oe-windows-acc-setup.yml

- hosts: windows-agents
  any_errors_fatal: true
  become_method: runas
  tasks:
    - import_role:
        name: windows/jenkins
        tasks_from: slave-setup.yml

    - import_role:
        name: windows/validation
        tasks_from: slave-validation.yml
